#!/usr/bin/env node
/**
 * Extract submission data from a Word document generated by export-word.js
 * and recreate the submissions-disbursements.json file
 */

const fs = require('fs');
const path = require('path');
const AdmZip = require('adm-zip');

// The Word file is a ZIP containing XML
const wordFile = process.argv[2] || './Disbursement-DataSheet.docx';

if (!fs.existsSync(wordFile)) {
  console.error(`❌ Word file not found: ${wordFile}`);
  process.exit(1);
}

try {
  // Extract ZIP
  const zip = new AdmZip(wordFile);
  const docXml = zip.readAsText('word/document.xml');
  
  // Parse XML to extract tables (Word stores data in tables)
  // The format is: Submission #N table followed by Related Items table
  
  const submissions = [];
  let currentSubmission = null;
  let inFieldsTable = false;
  let inRelatedTable = false;
  
  // This is complex XML parsing, so we'll use regex to find text content
  // Extract all text nodes
  const textMatches = docXml.match(/<w:t[^>]*>([^<]*)<\/w:t>/g) || [];
  const texts = textMatches.map(t => t.replace(/<w:t[^>]*>|<\/w:t>/g, ''));
  
  console.log(`Total text elements: ${texts.length}`);
  console.log(`First 50 elements:`, texts.slice(0, 50));
  
  // Parse the submission structure
  for (let i = 0; i < texts.length; i++) {
    const text = texts[i];
    
    // Look for submission headers "Submission #N"
    if (text.startsWith('Submission #')) {
      if (currentSubmission && currentSubmission.fields) {
        submissions.push(currentSubmission);
      }
      currentSubmission = {
        id: Date.now().toString(36) + Math.random().toString(36).slice(2, 6),
        savedAt: new Date().toISOString(),
        data: {
          fields: [],
          crudTables: []
        }
      };
      continue;
    }
    
    // Field parsing: look for label-value pairs
    if (currentSubmission && i + 1 < texts.length) {
      const next = texts[i + 1];
      // Skip headers, dates, and metadata
      if (!text.includes('Submission') && !text.includes('Generated') && 
          !text.includes('Click to edit') && text.length > 0 && next && next.length > 0) {
        // This might be a label-value pair
        currentSubmission.data.fields.push({
          label: text.trim(),
          value: next.trim()
        });
      }
    }
  }
  
  if (currentSubmission && currentSubmission.data.fields.length > 0) {
    submissions.push(currentSubmission);
  }
  
  console.log(`\n✓ Extracted ${submissions.length} submissions`);
  
  if (submissions.length === 0) {
    console.warn('⚠️  No submissions found in Word document');
    console.warn('Raw XML length:', docXml.length);
    console.log('Sample XML:', docXml.substring(0, 500));
  }
  
} catch (err) {
  console.error('❌ Error processing Word file:', err.message);
  process.exit(1);
}
